filter:
    paths: [src/*]
build:
    dependencies:
        before:
            - composer create-project mvc5/application build --stability dev --dev --keep-vcs
    tests:
        after:
          - php -d opcache.enable=1 -d opcache.enable_cli=1 build/public/index.php >/dev/null
          - php -d opcache.enable=0 -d opcache.enable_cli=0 build/public/index.php >/dev/null
          - php -n build/public/index.php >/dev/null

        override:
            -
                command: 'phpunit --configuration build/phpunit.xml --coverage-clover build/logs/clover.clover'
                coverage:
                    file: 'build/logs/clover.clover'
                    format: 'php-clover'
