build:
    dependencies:
        before:
            - composer create-project mvc5/application build --stability dev --dev --keep-vcs
    tests:
        after:
            - ls -la build/logs
        override:
            -
                command: 'phpunit --configuration build/phpunit.xml'
                coverage:
                    file: 'build/logs/clover.clover'
                    format: 'php-clover'
