language: php

php:
  - 5.5
  - 5.6

matrix:
  include:
    - php: 5.5
      env: DEPS=lowest

before_script:
  - composer selfupdate
  - if [ "$DEPS" = "lowest" ]; then composer update --prefer-lowest -n; else composer install -n; fi;
  - composer create-project mvc5/application build --stability dev --dev --keep-vcs

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/coverage.clover

script:
  - phpunit --configuration build/phpunit.xml

notifications:
  email: false
