title: Mvc5 Framework
tagline: A PHP 5.5 framework with dependency injection, events, and named arguments
author:
name: devosc
email: devosc@gmail.com
github: devosc
twitter: devosc

root: /framework
permalink: /framework/:year/:month/:day/:title/

baseurl: /framework